// <auto-generated />
// Generated by tools/abi_framework/generators/lumenrtc_csharp_handles.py
using System;
using System.Runtime.InteropServices;

namespace LumenRTC;

public sealed partial class AudioDevice
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_audio_device_release(handle);
        return true;
    }
}

public sealed partial class AudioSink
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_audio_sink_release(handle);
        return true;
    }
}

public sealed partial class AudioSource
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_audio_source_release(handle);
        return true;
    }
}

public sealed partial class AudioTrack
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_audio_track_release(handle);
        return true;
    }
}

public sealed partial class DataChannel
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_data_channel_release(handle);
        return true;
    }
}

public sealed partial class DesktopCapturer
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_desktop_capturer_release(handle);
        return true;
    }
}

public sealed partial class DesktopDevice
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_desktop_device_release(handle);
        return true;
    }
}

public sealed partial class DesktopMediaList
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_desktop_media_list_release(handle);
        return true;
    }
}

public sealed partial class DtmfSender
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_dtmf_sender_release(handle);
        return true;
    }
}

public sealed partial class MediaConstraints
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_media_constraints_release(handle);
        return true;
    }
}

public sealed partial class MediaSource
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_media_source_release(handle);
        return true;
    }
}

public sealed partial class MediaStream
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_media_stream_release(handle);
        return true;
    }
}

public sealed partial class PeerConnection
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_peer_connection_release(handle);
        return true;
    }
}

public sealed partial class PeerConnectionFactory
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_factory_release(handle);
        return true;
    }
}

public sealed partial class RtpReceiver
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_rtp_receiver_release(handle);
        return true;
    }
}

public sealed partial class RtpSender
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_rtp_sender_release(handle);
        return true;
    }
}

public sealed partial class RtpTransceiver
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_rtp_transceiver_release(handle);
        return true;
    }
}

public sealed partial class VideoCapturer
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_capturer_release(handle);
        return true;
    }
}

public sealed partial class VideoDevice
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_device_release(handle);
        return true;
    }
}

public sealed partial class VideoFrame
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_frame_release(handle);
        return true;
    }
}

public sealed partial class VideoSink
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_sink_release(handle);
        return true;
    }
}

public sealed partial class VideoSource
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_source_release(handle);
        return true;
    }
}

public sealed partial class VideoTrack
{
    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        LumenRTC.Interop.NativeMethods.lrtc_video_track_release(handle);
        return true;
    }
}
