// <auto-generated />
// Generated by tools/lumenrtc_codegen/lumenrtc_native_exports.py
#include "lumenrtc.h"
#include "lumenrtc_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_abi_version_major(void) {
    return lrtc_impl_abi_version_major();
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_abi_version_minor(void) {
    return lrtc_impl_abi_version_minor();
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_abi_version_patch(void) {
    return lrtc_impl_abi_version_patch();
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_abi_version_string(char* buffer, uint32_t buffer_len) {
    return lrtc_impl_abi_version_string(buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_microphone_volume(lrtc_audio_device_t* device, uint32_t* volume) {
    return lrtc_impl_audio_device_microphone_volume(device, volume);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_playout_device_name(lrtc_audio_device_t* device, uint16_t index, char* name, uint32_t name_len, char* guid, uint32_t guid_len) {
    return lrtc_impl_audio_device_playout_device_name(device, index, name, name_len, guid, guid_len);
}

LUMENRTC_API int16_t LUMENRTC_CALL lrtc_audio_device_playout_devices(lrtc_audio_device_t* device) {
    return lrtc_impl_audio_device_playout_devices(device);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_recording_device_name(lrtc_audio_device_t* device, uint16_t index, char* name, uint32_t name_len, char* guid, uint32_t guid_len) {
    return lrtc_impl_audio_device_recording_device_name(device, index, name, name_len, guid, guid_len);
}

LUMENRTC_API int16_t LUMENRTC_CALL lrtc_audio_device_recording_devices(lrtc_audio_device_t* device) {
    return lrtc_impl_audio_device_recording_devices(device);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_device_release(lrtc_audio_device_t* device) {
    lrtc_impl_audio_device_release(device);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_set_microphone_volume(lrtc_audio_device_t* device, uint32_t volume) {
    return lrtc_impl_audio_device_set_microphone_volume(device, volume);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_set_playout_device(lrtc_audio_device_t* device, uint16_t index) {
    return lrtc_impl_audio_device_set_playout_device(device, index);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_set_recording_device(lrtc_audio_device_t* device, uint16_t index) {
    return lrtc_impl_audio_device_set_recording_device(device, index);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_set_speaker_volume(lrtc_audio_device_t* device, uint32_t volume) {
    return lrtc_impl_audio_device_set_speaker_volume(device, volume);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_device_speaker_volume(lrtc_audio_device_t* device, uint32_t* volume) {
    return lrtc_impl_audio_device_speaker_volume(device, volume);
}

LUMENRTC_API lrtc_audio_sink_t* LUMENRTC_CALL lrtc_audio_sink_create(const lrtc_audio_sink_callbacks_t* callbacks, void* user_data) {
    return lrtc_impl_audio_sink_create(callbacks, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_sink_release(lrtc_audio_sink_t* sink) {
    lrtc_impl_audio_sink_release(sink);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_source_capture_frame(lrtc_audio_source_t* source, const void* audio_data, int bits_per_sample, int sample_rate, size_t number_of_channels, size_t number_of_frames) {
    lrtc_impl_audio_source_capture_frame(source, audio_data, bits_per_sample, sample_rate, number_of_channels, number_of_frames);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_source_release(lrtc_audio_source_t* source) {
    lrtc_impl_audio_source_release(source);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_track_add_sink(lrtc_audio_track_t* track, lrtc_audio_sink_t* sink) {
    lrtc_impl_audio_track_add_sink(track, sink);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_audio_track_get_enabled(lrtc_audio_track_t* track) {
    return lrtc_impl_audio_track_get_enabled(track);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_audio_track_get_id(lrtc_audio_track_t* track, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_audio_track_get_id(track, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_audio_track_get_state(lrtc_audio_track_t* track) {
    return lrtc_impl_audio_track_get_state(track);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_track_release(lrtc_audio_track_t* track) {
    lrtc_impl_audio_track_release(track);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_track_remove_sink(lrtc_audio_track_t* track, lrtc_audio_sink_t* sink) {
    lrtc_impl_audio_track_remove_sink(track, sink);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_audio_track_set_enabled(lrtc_audio_track_t* track, int enabled) {
    return lrtc_impl_audio_track_set_enabled(track, enabled);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_audio_track_set_volume(lrtc_audio_track_t* track, double volume) {
    lrtc_impl_audio_track_set_volume(track, volume);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_data_channel_close(lrtc_data_channel_t* channel) {
    lrtc_impl_data_channel_close(channel);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_data_channel_release(lrtc_data_channel_t* channel) {
    lrtc_impl_data_channel_release(channel);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_data_channel_send(lrtc_data_channel_t* channel, const uint8_t* data, uint32_t size, int binary) {
    lrtc_impl_data_channel_send(channel, data, size, binary);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_data_channel_set_callbacks(lrtc_data_channel_t* channel, const lrtc_data_channel_callbacks_t* callbacks, void* user_data) {
    lrtc_impl_data_channel_set_callbacks(channel, callbacks, user_data);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_desktop_capturer_is_running(lrtc_desktop_capturer_t* capturer) {
    return lrtc_impl_desktop_capturer_is_running(capturer);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_desktop_capturer_release(lrtc_desktop_capturer_t* capturer) {
    lrtc_impl_desktop_capturer_release(capturer);
}

LUMENRTC_API lrtc_desktop_capture_state LUMENRTC_CALL lrtc_desktop_capturer_start(lrtc_desktop_capturer_t* capturer, uint32_t fps) {
    return lrtc_impl_desktop_capturer_start(capturer, fps);
}

LUMENRTC_API lrtc_desktop_capture_state LUMENRTC_CALL lrtc_desktop_capturer_start_region(lrtc_desktop_capturer_t* capturer, uint32_t fps, uint32_t x, uint32_t y, uint32_t w, uint32_t h) {
    return lrtc_impl_desktop_capturer_start_region(capturer, fps, x, y, w, h);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_desktop_capturer_stop(lrtc_desktop_capturer_t* capturer) {
    lrtc_impl_desktop_capturer_stop(capturer);
}

LUMENRTC_API lrtc_desktop_capturer_t* LUMENRTC_CALL lrtc_desktop_device_create_capturer(lrtc_desktop_device_t* device, lrtc_media_source_t* source, bool show_cursor) {
    return lrtc_impl_desktop_device_create_capturer(device, source, show_cursor);
}

LUMENRTC_API lrtc_desktop_media_list_t* LUMENRTC_CALL lrtc_desktop_device_get_media_list(lrtc_desktop_device_t* device, lrtc_desktop_type type) {
    return lrtc_impl_desktop_device_get_media_list(device, type);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_desktop_device_release(lrtc_desktop_device_t* device) {
    lrtc_impl_desktop_device_release(device);
}

LUMENRTC_API lrtc_media_source_t* LUMENRTC_CALL lrtc_desktop_media_list_get_source(lrtc_desktop_media_list_t* list, int index) {
    return lrtc_impl_desktop_media_list_get_source(list, index);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_desktop_media_list_get_source_count(lrtc_desktop_media_list_t* list) {
    return lrtc_impl_desktop_media_list_get_source_count(list);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_desktop_media_list_release(lrtc_desktop_media_list_t* list) {
    lrtc_impl_desktop_media_list_release(list);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_desktop_media_list_update(lrtc_desktop_media_list_t* list, bool force_reload, bool get_thumbnail) {
    return lrtc_impl_desktop_media_list_update(list, force_reload, get_thumbnail);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_dtmf_sender_can_insert(lrtc_dtmf_sender_t* sender) {
    return lrtc_impl_dtmf_sender_can_insert(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_dtmf_sender_comma_delay(lrtc_dtmf_sender_t* sender) {
    return lrtc_impl_dtmf_sender_comma_delay(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_dtmf_sender_duration(lrtc_dtmf_sender_t* sender) {
    return lrtc_impl_dtmf_sender_duration(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_dtmf_sender_insert(lrtc_dtmf_sender_t* sender, const char* tones, int duration, int inter_tone_gap, int comma_delay) {
    return lrtc_impl_dtmf_sender_insert(sender, tones, duration, inter_tone_gap, comma_delay);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_dtmf_sender_inter_tone_gap(lrtc_dtmf_sender_t* sender) {
    return lrtc_impl_dtmf_sender_inter_tone_gap(sender);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_dtmf_sender_release(lrtc_dtmf_sender_t* sender) {
    lrtc_impl_dtmf_sender_release(sender);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_dtmf_sender_set_callbacks(lrtc_dtmf_sender_t* sender, const lrtc_dtmf_sender_callbacks_t* callbacks, void* user_data) {
    lrtc_impl_dtmf_sender_set_callbacks(sender, callbacks, user_data);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_dtmf_sender_tones(lrtc_dtmf_sender_t* sender, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_dtmf_sender_tones(sender, buffer, buffer_len);
}

LUMENRTC_API lrtc_factory_t* LUMENRTC_CALL lrtc_factory_create(void) {
    return lrtc_impl_factory_create();
}

LUMENRTC_API lrtc_audio_source_t* LUMENRTC_CALL lrtc_factory_create_audio_source(lrtc_factory_t* factory, const char* label, lrtc_audio_source_type source_type, const lrtc_audio_options_t* options) {
    return lrtc_impl_factory_create_audio_source(factory, label, source_type, options);
}

LUMENRTC_API lrtc_audio_track_t* LUMENRTC_CALL lrtc_factory_create_audio_track(lrtc_factory_t* factory, lrtc_audio_source_t* source, const char* track_id) {
    return lrtc_impl_factory_create_audio_track(factory, source, track_id);
}

LUMENRTC_API lrtc_video_source_t* LUMENRTC_CALL lrtc_factory_create_desktop_source(lrtc_factory_t* factory, lrtc_desktop_capturer_t* capturer, const char* label, lrtc_media_constraints_t* constraints) {
    return lrtc_impl_factory_create_desktop_source(factory, capturer, label, constraints);
}

LUMENRTC_API lrtc_media_stream_t* LUMENRTC_CALL lrtc_factory_create_stream(lrtc_factory_t* factory, const char* stream_id) {
    return lrtc_impl_factory_create_stream(factory, stream_id);
}

LUMENRTC_API lrtc_video_source_t* LUMENRTC_CALL lrtc_factory_create_video_source(lrtc_factory_t* factory, lrtc_video_capturer_t* capturer, const char* label, lrtc_media_constraints_t* constraints) {
    return lrtc_impl_factory_create_video_source(factory, capturer, label, constraints);
}

LUMENRTC_API lrtc_video_track_t* LUMENRTC_CALL lrtc_factory_create_video_track(lrtc_factory_t* factory, lrtc_video_source_t* source, const char* track_id) {
    return lrtc_impl_factory_create_video_track(factory, source, track_id);
}

LUMENRTC_API lrtc_audio_device_t* LUMENRTC_CALL lrtc_factory_get_audio_device(lrtc_factory_t* factory) {
    return lrtc_impl_factory_get_audio_device(factory);
}

LUMENRTC_API lrtc_desktop_device_t* LUMENRTC_CALL lrtc_factory_get_desktop_device(lrtc_factory_t* factory) {
    return lrtc_impl_factory_get_desktop_device(factory);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_factory_get_rtp_receiver_capabilities(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_factory_get_rtp_receiver_capabilities(factory, media_type, success, failure, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_factory_get_rtp_sender_capabilities(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_factory_get_rtp_sender_capabilities(factory, media_type, success, failure, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_factory_get_rtp_sender_codec_mime_types(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_factory_get_rtp_sender_codec_mime_types(factory, media_type, success, failure, user_data);
}

LUMENRTC_API lrtc_video_device_t* LUMENRTC_CALL lrtc_factory_get_video_device(lrtc_factory_t* factory) {
    return lrtc_impl_factory_get_video_device(factory);
}

LUMENRTC_API lrtc_result_t LUMENRTC_CALL lrtc_factory_initialize(lrtc_factory_t* factory) {
    return lrtc_impl_factory_initialize(factory);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_factory_release(lrtc_factory_t* factory) {
    lrtc_impl_factory_release(factory);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_factory_terminate(lrtc_factory_t* factory) {
    lrtc_impl_factory_terminate(factory);
}

LUMENRTC_API lrtc_result_t LUMENRTC_CALL lrtc_initialize(void) {
    return lrtc_impl_initialize();
}

LUMENRTC_API void LUMENRTC_CALL lrtc_logging_remove_callback(void) {
    lrtc_impl_logging_remove_callback();
}

LUMENRTC_API void LUMENRTC_CALL lrtc_logging_set_callback(int severity, lrtc_log_message_cb callback, void* user_data) {
    lrtc_impl_logging_set_callback(severity, callback, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_logging_set_min_level(int severity) {
    lrtc_impl_logging_set_min_level(severity);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_media_constraints_add_mandatory(lrtc_media_constraints_t* constraints, const char* key, const char* value) {
    lrtc_impl_media_constraints_add_mandatory(constraints, key, value);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_media_constraints_add_optional(lrtc_media_constraints_t* constraints, const char* key, const char* value) {
    lrtc_impl_media_constraints_add_optional(constraints, key, value);
}

LUMENRTC_API lrtc_media_constraints_t* LUMENRTC_CALL lrtc_media_constraints_create(void) {
    return lrtc_impl_media_constraints_create();
}

LUMENRTC_API void LUMENRTC_CALL lrtc_media_constraints_release(lrtc_media_constraints_t* constraints) {
    lrtc_impl_media_constraints_release(constraints);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_media_source_get_id(lrtc_media_source_t* source, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_media_source_get_id(source, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_media_source_get_name(lrtc_media_source_t* source, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_media_source_get_name(source, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_media_source_get_type(lrtc_media_source_t* source) {
    return lrtc_impl_media_source_get_type(source);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_media_source_release(lrtc_media_source_t* source) {
    lrtc_impl_media_source_release(source);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_media_stream_add_audio_track(lrtc_media_stream_t* stream, lrtc_audio_track_t* track) {
    return lrtc_impl_media_stream_add_audio_track(stream, track);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_media_stream_add_video_track(lrtc_media_stream_t* stream, lrtc_video_track_t* track) {
    return lrtc_impl_media_stream_add_video_track(stream, track);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_media_stream_get_id(lrtc_media_stream_t* stream, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_media_stream_get_id(stream, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_media_stream_get_label(lrtc_media_stream_t* stream, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_media_stream_get_label(stream, buffer, buffer_len);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_media_stream_release(lrtc_media_stream_t* stream) {
    lrtc_impl_media_stream_release(stream);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_media_stream_remove_audio_track(lrtc_media_stream_t* stream, lrtc_audio_track_t* track) {
    return lrtc_impl_media_stream_remove_audio_track(stream, track);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_media_stream_remove_video_track(lrtc_media_stream_t* stream, lrtc_video_track_t* track) {
    return lrtc_impl_media_stream_remove_video_track(stream, track);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_add_audio_track(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const char** stream_ids, uint32_t stream_id_count) {
    return lrtc_impl_peer_connection_add_audio_track(pc, track, stream_ids, stream_id_count);
}

LUMENRTC_API lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_peer_connection_add_audio_track_sender(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const char** stream_ids, uint32_t stream_id_count) {
    return lrtc_impl_peer_connection_add_audio_track_sender(pc, track, stream_ids, stream_id_count);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_audio_track_transceiver(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track) {
    return lrtc_impl_peer_connection_add_audio_track_transceiver(pc, track);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_audio_track_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const lrtc_rtp_transceiver_init_t* init) {
    return lrtc_impl_peer_connection_add_audio_track_transceiver_with_init(pc, track, init);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_add_ice_candidate(lrtc_peer_connection_t* pc, const char* sdp_mid, int sdp_mline_index, const char* candidate) {
    lrtc_impl_peer_connection_add_ice_candidate(pc, sdp_mid, sdp_mline_index, candidate);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_add_ice_candidate_ex(lrtc_peer_connection_t* pc, const char* sdp_mid, int sdp_mline_index, const char* candidate) {
    return lrtc_impl_peer_connection_add_ice_candidate_ex(pc, sdp_mid, sdp_mline_index, candidate);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_peer_connection_add_stream(lrtc_peer_connection_t* pc, lrtc_media_stream_t* stream) {
    return lrtc_impl_peer_connection_add_stream(pc, stream);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_transceiver(lrtc_peer_connection_t* pc, lrtc_media_type media_type) {
    return lrtc_impl_peer_connection_add_transceiver(pc, media_type);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_media_type media_type, const lrtc_rtp_transceiver_init_t* init) {
    return lrtc_impl_peer_connection_add_transceiver_with_init(pc, media_type, init);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_add_video_track(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const char** stream_ids, uint32_t stream_id_count) {
    return lrtc_impl_peer_connection_add_video_track(pc, track, stream_ids, stream_id_count);
}

LUMENRTC_API lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_peer_connection_add_video_track_sender(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const char** stream_ids, uint32_t stream_id_count) {
    return lrtc_impl_peer_connection_add_video_track_sender(pc, track, stream_ids, stream_id_count);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_video_track_transceiver(lrtc_peer_connection_t* pc, lrtc_video_track_t* track) {
    return lrtc_impl_peer_connection_add_video_track_transceiver(pc, track);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_add_video_track_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const lrtc_rtp_transceiver_init_t* init) {
    return lrtc_impl_peer_connection_add_video_track_transceiver_with_init(pc, track, init);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_close(lrtc_peer_connection_t* pc) {
    lrtc_impl_peer_connection_close(pc);
}

LUMENRTC_API lrtc_peer_connection_t* LUMENRTC_CALL lrtc_peer_connection_create(lrtc_factory_t* factory, const lrtc_rtc_config_t* config, lrtc_media_constraints_t* constraints, const lrtc_peer_connection_callbacks_t* callbacks, void* user_data) {
    return lrtc_impl_peer_connection_create(factory, config, constraints, callbacks, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_create_answer(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data, lrtc_media_constraints_t* constraints) {
    lrtc_impl_peer_connection_create_answer(pc, success, failure, user_data, constraints);
}

LUMENRTC_API lrtc_data_channel_t* LUMENRTC_CALL lrtc_peer_connection_create_data_channel(lrtc_peer_connection_t* pc, const char* label, int ordered, int reliable, int max_retransmit_time, int max_retransmits, const char* protocol, int negotiated, int id) {
    return lrtc_impl_peer_connection_create_data_channel(pc, label, ordered, reliable, max_retransmit_time, max_retransmits, protocol, negotiated, id);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_create_offer(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data, lrtc_media_constraints_t* constraints) {
    lrtc_impl_peer_connection_create_offer(pc, success, failure, user_data, constraints);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_get_local_description(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data) {
    lrtc_impl_peer_connection_get_local_description(pc, success, failure, user_data);
}

LUMENRTC_API lrtc_rtp_receiver_t* LUMENRTC_CALL lrtc_peer_connection_get_receiver(lrtc_peer_connection_t* pc, uint32_t index) {
    return lrtc_impl_peer_connection_get_receiver(pc, index);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_get_receiver_stats(lrtc_peer_connection_t* pc, lrtc_rtp_receiver_t* receiver, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_peer_connection_get_receiver_stats(pc, receiver, success, failure, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_get_remote_description(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data) {
    lrtc_impl_peer_connection_get_remote_description(pc, success, failure, user_data);
}

LUMENRTC_API lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_peer_connection_get_sender(lrtc_peer_connection_t* pc, uint32_t index) {
    return lrtc_impl_peer_connection_get_sender(pc, index);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_get_sender_stats(lrtc_peer_connection_t* pc, lrtc_rtp_sender_t* sender, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_peer_connection_get_sender_stats(pc, sender, success, failure, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_get_stats(lrtc_peer_connection_t* pc, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data) {
    lrtc_impl_peer_connection_get_stats(pc, success, failure, user_data);
}

LUMENRTC_API lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_peer_connection_get_transceiver(lrtc_peer_connection_t* pc, uint32_t index) {
    return lrtc_impl_peer_connection_get_transceiver(pc, index);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_peer_connection_receiver_count(lrtc_peer_connection_t* pc) {
    return lrtc_impl_peer_connection_receiver_count(pc);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_release(lrtc_peer_connection_t* pc) {
    lrtc_impl_peer_connection_release(pc);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_peer_connection_remove_stream(lrtc_peer_connection_t* pc, lrtc_media_stream_t* stream) {
    return lrtc_impl_peer_connection_remove_stream(pc, stream);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_remove_track(lrtc_peer_connection_t* pc, lrtc_rtp_sender_t* sender) {
    return lrtc_impl_peer_connection_remove_track(pc, sender);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_restart_ice(lrtc_peer_connection_t* pc) {
    lrtc_impl_peer_connection_restart_ice(pc);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_peer_connection_sender_count(lrtc_peer_connection_t* pc) {
    return lrtc_impl_peer_connection_sender_count(pc);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_set_callbacks(lrtc_peer_connection_t* pc, const lrtc_peer_connection_callbacks_t* callbacks, void* user_data) {
    lrtc_impl_peer_connection_set_callbacks(pc, callbacks, user_data);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_set_codec_preferences(lrtc_peer_connection_t* pc, lrtc_media_type media_type, const char** mime_types, uint32_t mime_type_count) {
    return lrtc_impl_peer_connection_set_codec_preferences(pc, media_type, mime_types, mime_type_count);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_set_local_description(lrtc_peer_connection_t* pc, const char* sdp, const char* type, lrtc_void_cb success, lrtc_sdp_error_cb failure, void* user_data) {
    lrtc_impl_peer_connection_set_local_description(pc, sdp, type, success, failure, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_peer_connection_set_remote_description(lrtc_peer_connection_t* pc, const char* sdp, const char* type, lrtc_void_cb success, lrtc_sdp_error_cb failure, void* user_data) {
    lrtc_impl_peer_connection_set_remote_description(pc, sdp, type, success, failure, user_data);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_peer_connection_set_transceiver_codec_preferences(lrtc_peer_connection_t* pc, lrtc_rtp_transceiver_t* transceiver, const char** mime_types, uint32_t mime_type_count) {
    return lrtc_impl_peer_connection_set_transceiver_codec_preferences(pc, transceiver, mime_types, mime_type_count);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_peer_connection_transceiver_count(lrtc_peer_connection_t* pc) {
    return lrtc_impl_peer_connection_transceiver_count(pc);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_receiver_encoding_count(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_encoding_count(receiver);
}

LUMENRTC_API lrtc_audio_track_t* LUMENRTC_CALL lrtc_rtp_receiver_get_audio_track(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_get_audio_track(receiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_receiver_get_degradation_preference(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_get_degradation_preference(receiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_receiver_get_dtls_info(lrtc_rtp_receiver_t* receiver, lrtc_dtls_transport_info_t* info) {
    return lrtc_impl_rtp_receiver_get_dtls_info(receiver, info);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_receiver_get_encoding_info(lrtc_rtp_receiver_t* receiver, uint32_t index, lrtc_rtp_encoding_info_t* info) {
    return lrtc_impl_rtp_receiver_get_encoding_info(receiver, index, info);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_receiver_get_encoding_rid(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_receiver_get_encoding_rid(receiver, index, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_receiver_get_encoding_scalability_mode(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_receiver_get_encoding_scalability_mode(receiver, index, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_receiver_get_id(lrtc_rtp_receiver_t* receiver, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_receiver_get_id(receiver, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_receiver_get_media_type(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_get_media_type(receiver);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_receiver_get_parameters_mid(lrtc_rtp_receiver_t* receiver, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_receiver_get_parameters_mid(receiver, buffer, buffer_len);
}

LUMENRTC_API lrtc_media_stream_t* LUMENRTC_CALL lrtc_rtp_receiver_get_stream(lrtc_rtp_receiver_t* receiver, uint32_t index) {
    return lrtc_impl_rtp_receiver_get_stream(receiver, index);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_receiver_get_stream_id(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_receiver_get_stream_id(receiver, index, buffer, buffer_len);
}

LUMENRTC_API lrtc_video_track_t* LUMENRTC_CALL lrtc_rtp_receiver_get_video_track(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_get_video_track(receiver);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_rtp_receiver_release(lrtc_rtp_receiver_t* receiver) {
    lrtc_impl_rtp_receiver_release(receiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_receiver_set_jitter_buffer_min_delay(lrtc_rtp_receiver_t* receiver, double delay_seconds) {
    return lrtc_impl_rtp_receiver_set_jitter_buffer_min_delay(receiver, delay_seconds);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_receiver_stream_count(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_stream_count(receiver);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_receiver_stream_id_count(lrtc_rtp_receiver_t* receiver) {
    return lrtc_impl_rtp_receiver_stream_id_count(receiver);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_sender_encoding_count(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_encoding_count(sender);
}

LUMENRTC_API lrtc_audio_track_t* LUMENRTC_CALL lrtc_rtp_sender_get_audio_track(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_audio_track(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_get_degradation_preference(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_degradation_preference(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_get_dtls_info(lrtc_rtp_sender_t* sender, lrtc_dtls_transport_info_t* info) {
    return lrtc_impl_rtp_sender_get_dtls_info(sender, info);
}

LUMENRTC_API lrtc_dtmf_sender_t* LUMENRTC_CALL lrtc_rtp_sender_get_dtmf_sender(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_dtmf_sender(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_get_encoding_info(lrtc_rtp_sender_t* sender, uint32_t index, lrtc_rtp_encoding_info_t* info) {
    return lrtc_impl_rtp_sender_get_encoding_info(sender, index, info);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_sender_get_encoding_rid(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_sender_get_encoding_rid(sender, index, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_sender_get_encoding_scalability_mode(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_sender_get_encoding_scalability_mode(sender, index, buffer, buffer_len);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_sender_get_id(lrtc_rtp_sender_t* sender, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_sender_get_id(sender, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_get_media_type(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_media_type(sender);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_sender_get_parameters_mid(lrtc_rtp_sender_t* sender, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_sender_get_parameters_mid(sender, buffer, buffer_len);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_sender_get_ssrc(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_ssrc(sender);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_sender_get_stream_id(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_sender_get_stream_id(sender, index, buffer, buffer_len);
}

LUMENRTC_API lrtc_video_track_t* LUMENRTC_CALL lrtc_rtp_sender_get_video_track(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_get_video_track(sender);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_rtp_sender_release(lrtc_rtp_sender_t* sender) {
    lrtc_impl_rtp_sender_release(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_replace_audio_track(lrtc_rtp_sender_t* sender, lrtc_audio_track_t* track) {
    return lrtc_impl_rtp_sender_replace_audio_track(sender, track);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_replace_video_track(lrtc_rtp_sender_t* sender, lrtc_video_track_t* track) {
    return lrtc_impl_rtp_sender_replace_video_track(sender, track);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_set_encoding_parameters(lrtc_rtp_sender_t* sender, const lrtc_rtp_encoding_settings_t* settings) {
    return lrtc_impl_rtp_sender_set_encoding_parameters(sender, settings);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_set_encoding_parameters_at(lrtc_rtp_sender_t* sender, uint32_t index, const lrtc_rtp_encoding_settings_t* settings) {
    return lrtc_impl_rtp_sender_set_encoding_parameters_at(sender, index, settings);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_sender_set_stream_ids(lrtc_rtp_sender_t* sender, const char** stream_ids, uint32_t stream_id_count) {
    return lrtc_impl_rtp_sender_set_stream_ids(sender, stream_ids, stream_id_count);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_rtp_sender_stream_id_count(lrtc_rtp_sender_t* sender) {
    return lrtc_impl_rtp_sender_stream_id_count(sender);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_current_direction(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_current_direction(transceiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_direction(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_direction(transceiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_fired_direction(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_fired_direction(transceiver);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_transceiver_get_id(lrtc_rtp_transceiver_t* transceiver, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_transceiver_get_id(transceiver, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_media_type(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_media_type(transceiver);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_rtp_transceiver_get_mid(lrtc_rtp_transceiver_t* transceiver, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_rtp_transceiver_get_mid(transceiver, buffer, buffer_len);
}

LUMENRTC_API lrtc_rtp_receiver_t* LUMENRTC_CALL lrtc_rtp_transceiver_get_receiver(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_receiver(transceiver);
}

LUMENRTC_API lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_rtp_transceiver_get_sender(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_sender(transceiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_stopped(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_stopped(transceiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_get_stopping(lrtc_rtp_transceiver_t* transceiver) {
    return lrtc_impl_rtp_transceiver_get_stopping(transceiver);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_rtp_transceiver_release(lrtc_rtp_transceiver_t* transceiver) {
    lrtc_impl_rtp_transceiver_release(transceiver);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_set_direction(lrtc_rtp_transceiver_t* transceiver, int direction, char* error, uint32_t error_len) {
    return lrtc_impl_rtp_transceiver_set_direction(transceiver, direction, error, error_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_rtp_transceiver_stop(lrtc_rtp_transceiver_t* transceiver, char* error, uint32_t error_len) {
    return lrtc_impl_rtp_transceiver_stop(transceiver, error, error_len);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_terminate(void) {
    lrtc_impl_terminate();
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_video_capturer_capture_started(lrtc_video_capturer_t* capturer) {
    return lrtc_impl_video_capturer_capture_started(capturer);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_capturer_release(lrtc_video_capturer_t* capturer) {
    lrtc_impl_video_capturer_release(capturer);
}

LUMENRTC_API bool LUMENRTC_CALL lrtc_video_capturer_start(lrtc_video_capturer_t* capturer) {
    return lrtc_impl_video_capturer_start(capturer);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_capturer_stop(lrtc_video_capturer_t* capturer) {
    lrtc_impl_video_capturer_stop(capturer);
}

LUMENRTC_API lrtc_video_capturer_t* LUMENRTC_CALL lrtc_video_device_create_capturer(lrtc_video_device_t* device, const char* name, uint32_t index, size_t width, size_t height, size_t target_fps) {
    return lrtc_impl_video_device_create_capturer(device, name, index, width, height, target_fps);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_video_device_get_device_name(lrtc_video_device_t* device, uint32_t index, char* name, uint32_t name_length, char* unique_id, uint32_t unique_id_length) {
    return lrtc_impl_video_device_get_device_name(device, index, name, name_length, unique_id, unique_id_length);
}

LUMENRTC_API uint32_t LUMENRTC_CALL lrtc_video_device_number_of_devices(lrtc_video_device_t* device) {
    return lrtc_impl_video_device_number_of_devices(device);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_device_release(lrtc_video_device_t* device) {
    lrtc_impl_video_device_release(device);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_copy_i420(lrtc_video_frame_t* frame, uint8_t* dst_y, int dst_stride_y, uint8_t* dst_u, int dst_stride_u, uint8_t* dst_v, int dst_stride_v) {
    return lrtc_impl_video_frame_copy_i420(frame, dst_y, dst_stride_y, dst_u, dst_stride_u, dst_v, dst_stride_v);
}

LUMENRTC_API const uint8_t* LUMENRTC_CALL lrtc_video_frame_data_u(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_data_u(frame);
}

LUMENRTC_API const uint8_t* LUMENRTC_CALL lrtc_video_frame_data_v(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_data_v(frame);
}

LUMENRTC_API const uint8_t* LUMENRTC_CALL lrtc_video_frame_data_y(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_data_y(frame);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_height(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_height(frame);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_frame_release(lrtc_video_frame_t* frame) {
    lrtc_impl_video_frame_release(frame);
}

LUMENRTC_API lrtc_video_frame_t* LUMENRTC_CALL lrtc_video_frame_retain(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_retain(frame);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_stride_u(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_stride_u(frame);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_stride_v(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_stride_v(frame);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_stride_y(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_stride_y(frame);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_to_argb(lrtc_video_frame_t* frame, uint8_t* dst_argb, int dst_stride_argb, int dest_width, int dest_height, int format) {
    return lrtc_impl_video_frame_to_argb(frame, dst_argb, dst_stride_argb, dest_width, dest_height, format);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_frame_width(lrtc_video_frame_t* frame) {
    return lrtc_impl_video_frame_width(frame);
}

LUMENRTC_API lrtc_video_sink_t* LUMENRTC_CALL lrtc_video_sink_create(const lrtc_video_sink_callbacks_t* callbacks, void* user_data) {
    return lrtc_impl_video_sink_create(callbacks, user_data);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_sink_release(lrtc_video_sink_t* sink) {
    lrtc_impl_video_sink_release(sink);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_source_release(lrtc_video_source_t* source) {
    lrtc_impl_video_source_release(source);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_track_add_sink(lrtc_video_track_t* track, lrtc_video_sink_t* sink) {
    lrtc_impl_video_track_add_sink(track, sink);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_track_get_enabled(lrtc_video_track_t* track) {
    return lrtc_impl_video_track_get_enabled(track);
}

LUMENRTC_API int32_t LUMENRTC_CALL lrtc_video_track_get_id(lrtc_video_track_t* track, char* buffer, uint32_t buffer_len) {
    return lrtc_impl_video_track_get_id(track, buffer, buffer_len);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_track_get_state(lrtc_video_track_t* track) {
    return lrtc_impl_video_track_get_state(track);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_track_release(lrtc_video_track_t* track) {
    lrtc_impl_video_track_release(track);
}

LUMENRTC_API void LUMENRTC_CALL lrtc_video_track_remove_sink(lrtc_video_track_t* track, lrtc_video_sink_t* sink) {
    lrtc_impl_video_track_remove_sink(track, sink);
}

LUMENRTC_API int LUMENRTC_CALL lrtc_video_track_set_enabled(lrtc_video_track_t* track, int enabled) {
    return lrtc_impl_video_track_set_enabled(track, enabled);
}

#ifdef __cplusplus
}
#endif
