/* lumenrtc_layout_probe.c — generated by abi_framework layout_probe_generator */
/* Compile this file to verify that struct fields in the IDL match the header. */
/* Any compile error here means the C header has drifted from the IDL snapshot. */

#include "lumenrtc.h"
#include <stddef.h>
#include <stdint.h>

/* --- field existence checks --- */
/* Each function below will fail to compile if a field is renamed or removed. */

static void abi_layout_check_lrtc_audio_options_t(void) {
    lrtc_audio_options_t _s;
    (void)_s;
    (void)_s.echo_cancellation;  /* field must exist */
    (void)_s.auto_gain_control;  /* field must exist */
    (void)_s.noise_suppression;  /* field must exist */
    (void)_s.highpass_filter;  /* field must exist */
    /* lrtc_audio_options_t: 4 field(s) expected */
}

static void abi_layout_check_lrtc_audio_sink_callbacks_t(void) {
    lrtc_audio_sink_callbacks_t _s;
    (void)_s;
    (void)_s.on_data;  /* field must exist */
    /* lrtc_audio_sink_callbacks_t: 1 field(s) expected */
}

static void abi_layout_check_lrtc_data_channel_callbacks_t(void) {
    lrtc_data_channel_callbacks_t _s;
    (void)_s;
    (void)_s.on_state_change;  /* field must exist */
    (void)_s.on_message;  /* field must exist */
    /* lrtc_data_channel_callbacks_t: 2 field(s) expected */
}

static void abi_layout_check_lrtc_dtls_transport_info_t(void) {
    lrtc_dtls_transport_info_t _s;
    (void)_s;
    (void)_s.state;  /* field must exist */
    (void)_s.ssl_cipher_suite;  /* field must exist */
    (void)_s.srtp_cipher_suite;  /* field must exist */
    /* lrtc_dtls_transport_info_t: 3 field(s) expected */
}

static void abi_layout_check_lrtc_dtmf_sender_callbacks_t(void) {
    lrtc_dtmf_sender_callbacks_t _s;
    (void)_s;
    (void)_s.on_tone_change;  /* field must exist */
    /* lrtc_dtmf_sender_callbacks_t: 1 field(s) expected */
}

static void abi_layout_check_lrtc_ice_server_t(void) {
    lrtc_ice_server_t _s;
    (void)_s;
    (void)_s.uri;  /* field must exist */
    (void)_s.username;  /* field must exist */
    (void)_s.password;  /* field must exist */
    /* lrtc_ice_server_t: 3 field(s) expected */
}

static void abi_layout_check_lrtc_peer_connection_callbacks_t(void) {
    lrtc_peer_connection_callbacks_t _s;
    (void)_s;
    (void)_s.on_signaling_state;  /* field must exist */
    (void)_s.on_peer_connection_state;  /* field must exist */
    (void)_s.on_ice_gathering_state;  /* field must exist */
    (void)_s.on_ice_connection_state;  /* field must exist */
    (void)_s.on_ice_candidate;  /* field must exist */
    (void)_s.on_data_channel;  /* field must exist */
    (void)_s.on_video_track;  /* field must exist */
    (void)_s.on_audio_track;  /* field must exist */
    (void)_s.on_track;  /* field must exist */
    (void)_s.on_remove_track;  /* field must exist */
    (void)_s.on_renegotiation_needed;  /* field must exist */
    /* lrtc_peer_connection_callbacks_t: 11 field(s) expected */
}

static void abi_layout_check_lrtc_rtc_config_t(void) {
    lrtc_rtc_config_t _s;
    (void)_s;
    (void)_s.ice_servers;  /* field must exist */
    (void)_s.ice_server_count;  /* field must exist */
    (void)_s.ice_transports_type;  /* field must exist */
    (void)_s.bundle_policy;  /* field must exist */
    (void)_s.rtcp_mux_policy;  /* field must exist */
    (void)_s.candidate_network_policy;  /* field must exist */
    (void)_s.tcp_candidate_policy;  /* field must exist */
    (void)_s.ice_candidate_pool_size;  /* field must exist */
    (void)_s.srtp_type;  /* field must exist */
    (void)_s.sdp_semantics;  /* field must exist */
    (void)_s.offer_to_receive_audio;  /* field must exist */
    (void)_s.offer_to_receive_video;  /* field must exist */
    (void)_s.disable_ipv6;  /* field must exist */
    (void)_s.disable_ipv6_on_wifi;  /* field must exist */
    (void)_s.max_ipv6_networks;  /* field must exist */
    (void)_s.disable_link_local_networks;  /* field must exist */
    (void)_s.screencast_min_bitrate;  /* field must exist */
    (void)_s.enable_dscp;  /* field must exist */
    (void)_s.use_rtp_mux;  /* field must exist */
    (void)_s.local_audio_bandwidth;  /* field must exist */
    (void)_s.local_video_bandwidth;  /* field must exist */
    /* lrtc_rtc_config_t: 21 field(s) expected */
}

static void abi_layout_check_lrtc_rtp_encoding_info_t(void) {
    lrtc_rtp_encoding_info_t _s;
    (void)_s;
    (void)_s.ssrc;  /* field must exist */
    (void)_s.max_bitrate_bps;  /* field must exist */
    (void)_s.min_bitrate_bps;  /* field must exist */
    (void)_s.max_framerate;  /* field must exist */
    (void)_s.scale_resolution_down_by;  /* field must exist */
    (void)_s.active;  /* field must exist */
    (void)_s.bitrate_priority;  /* field must exist */
    (void)_s.network_priority;  /* field must exist */
    (void)_s.num_temporal_layers;  /* field must exist */
    (void)_s.adaptive_ptime;  /* field must exist */
    /* lrtc_rtp_encoding_info_t: 10 field(s) expected */
}

static void abi_layout_check_lrtc_rtp_encoding_settings_t(void) {
    lrtc_rtp_encoding_settings_t _s;
    (void)_s;
    (void)_s.max_bitrate_bps;  /* field must exist */
    (void)_s.min_bitrate_bps;  /* field must exist */
    (void)_s.max_framerate;  /* field must exist */
    (void)_s.scale_resolution_down_by;  /* field must exist */
    (void)_s.active;  /* field must exist */
    (void)_s.degradation_preference;  /* field must exist */
    (void)_s.bitrate_priority;  /* field must exist */
    (void)_s.network_priority;  /* field must exist */
    (void)_s.num_temporal_layers;  /* field must exist */
    (void)_s.scalability_mode;  /* field must exist */
    (void)_s.rid;  /* field must exist */
    (void)_s.adaptive_ptime;  /* field must exist */
    /* lrtc_rtp_encoding_settings_t: 12 field(s) expected */
}

static void abi_layout_check_lrtc_rtp_transceiver_init_t(void) {
    lrtc_rtp_transceiver_init_t _s;
    (void)_s;
    (void)_s.direction;  /* field must exist */
    (void)_s.stream_ids;  /* field must exist */
    (void)_s.stream_id_count;  /* field must exist */
    (void)_s.send_encodings;  /* field must exist */
    (void)_s.send_encoding_count;  /* field must exist */
    /* lrtc_rtp_transceiver_init_t: 5 field(s) expected */
}

static void abi_layout_check_lrtc_video_sink_callbacks_t(void) {
    lrtc_video_sink_callbacks_t _s;
    (void)_s;
    (void)_s.on_frame;  /* field must exist */
    /* lrtc_video_sink_callbacks_t: 1 field(s) expected */
}

/* --- top-level entry point (call from a test or just compile) --- */
static void abi_layout_probe_all(void) {
    abi_layout_check_lrtc_audio_options_t();
    abi_layout_check_lrtc_audio_sink_callbacks_t();
    abi_layout_check_lrtc_data_channel_callbacks_t();
    abi_layout_check_lrtc_dtls_transport_info_t();
    abi_layout_check_lrtc_dtmf_sender_callbacks_t();
    abi_layout_check_lrtc_ice_server_t();
    abi_layout_check_lrtc_peer_connection_callbacks_t();
    abi_layout_check_lrtc_rtc_config_t();
    abi_layout_check_lrtc_rtp_encoding_info_t();
    abi_layout_check_lrtc_rtp_encoding_settings_t();
    abi_layout_check_lrtc_rtp_transceiver_init_t();
    abi_layout_check_lrtc_video_sink_callbacks_t();
}
