#pragma once

#include "lumenrtc.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32_t LUMENRTC_CALL lrtc_impl_abi_version_major(void);
uint32_t LUMENRTC_CALL lrtc_impl_abi_version_minor(void);
uint32_t LUMENRTC_CALL lrtc_impl_abi_version_patch(void);
int32_t LUMENRTC_CALL lrtc_impl_abi_version_string(char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_microphone_volume(lrtc_audio_device_t* device, uint32_t* volume);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_playout_device_name(lrtc_audio_device_t* device, uint16_t index, char* name, uint32_t name_len, char* guid, uint32_t guid_len);
int16_t LUMENRTC_CALL lrtc_impl_audio_device_playout_devices(lrtc_audio_device_t* device);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_recording_device_name(lrtc_audio_device_t* device, uint16_t index, char* name, uint32_t name_len, char* guid, uint32_t guid_len);
int16_t LUMENRTC_CALL lrtc_impl_audio_device_recording_devices(lrtc_audio_device_t* device);
void LUMENRTC_CALL lrtc_impl_audio_device_release(lrtc_audio_device_t* device);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_set_microphone_volume(lrtc_audio_device_t* device, uint32_t volume);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_set_playout_device(lrtc_audio_device_t* device, uint16_t index);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_set_recording_device(lrtc_audio_device_t* device, uint16_t index);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_set_speaker_volume(lrtc_audio_device_t* device, uint32_t volume);
int32_t LUMENRTC_CALL lrtc_impl_audio_device_speaker_volume(lrtc_audio_device_t* device, uint32_t* volume);
lrtc_audio_sink_t* LUMENRTC_CALL lrtc_impl_audio_sink_create(const lrtc_audio_sink_callbacks_t* callbacks, void* user_data);
void LUMENRTC_CALL lrtc_impl_audio_sink_release(lrtc_audio_sink_t* sink);
void LUMENRTC_CALL lrtc_impl_audio_source_capture_frame(lrtc_audio_source_t* source, const void* audio_data, int bits_per_sample, int sample_rate, size_t number_of_channels, size_t number_of_frames);
void LUMENRTC_CALL lrtc_impl_audio_source_release(lrtc_audio_source_t* source);
void LUMENRTC_CALL lrtc_impl_audio_track_add_sink(lrtc_audio_track_t* track, lrtc_audio_sink_t* sink);
int LUMENRTC_CALL lrtc_impl_audio_track_get_enabled(lrtc_audio_track_t* track);
int32_t LUMENRTC_CALL lrtc_impl_audio_track_get_id(lrtc_audio_track_t* track, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_audio_track_get_state(lrtc_audio_track_t* track);
void LUMENRTC_CALL lrtc_impl_audio_track_release(lrtc_audio_track_t* track);
void LUMENRTC_CALL lrtc_impl_audio_track_remove_sink(lrtc_audio_track_t* track, lrtc_audio_sink_t* sink);
int LUMENRTC_CALL lrtc_impl_audio_track_set_enabled(lrtc_audio_track_t* track, int enabled);
void LUMENRTC_CALL lrtc_impl_audio_track_set_volume(lrtc_audio_track_t* track, double volume);
void LUMENRTC_CALL lrtc_impl_data_channel_close(lrtc_data_channel_t* channel);
void LUMENRTC_CALL lrtc_impl_data_channel_release(lrtc_data_channel_t* channel);
void LUMENRTC_CALL lrtc_impl_data_channel_send(lrtc_data_channel_t* channel, const uint8_t* data, uint32_t size, int binary);
void LUMENRTC_CALL lrtc_impl_data_channel_set_callbacks(lrtc_data_channel_t* channel, const lrtc_data_channel_callbacks_t* callbacks, void* user_data);
bool LUMENRTC_CALL lrtc_impl_desktop_capturer_is_running(lrtc_desktop_capturer_t* capturer);
void LUMENRTC_CALL lrtc_impl_desktop_capturer_release(lrtc_desktop_capturer_t* capturer);
lrtc_desktop_capture_state LUMENRTC_CALL lrtc_impl_desktop_capturer_start(lrtc_desktop_capturer_t* capturer, uint32_t fps);
lrtc_desktop_capture_state LUMENRTC_CALL lrtc_impl_desktop_capturer_start_region(lrtc_desktop_capturer_t* capturer, uint32_t fps, uint32_t x, uint32_t y, uint32_t w, uint32_t h);
void LUMENRTC_CALL lrtc_impl_desktop_capturer_stop(lrtc_desktop_capturer_t* capturer);
lrtc_desktop_capturer_t* LUMENRTC_CALL lrtc_impl_desktop_device_create_capturer(lrtc_desktop_device_t* device, lrtc_media_source_t* source, bool show_cursor);
lrtc_desktop_media_list_t* LUMENRTC_CALL lrtc_impl_desktop_device_get_media_list(lrtc_desktop_device_t* device, lrtc_desktop_type type);
void LUMENRTC_CALL lrtc_impl_desktop_device_release(lrtc_desktop_device_t* device);
lrtc_media_source_t* LUMENRTC_CALL lrtc_impl_desktop_media_list_get_source(lrtc_desktop_media_list_t* list, int index);
int LUMENRTC_CALL lrtc_impl_desktop_media_list_get_source_count(lrtc_desktop_media_list_t* list);
void LUMENRTC_CALL lrtc_impl_desktop_media_list_release(lrtc_desktop_media_list_t* list);
int32_t LUMENRTC_CALL lrtc_impl_desktop_media_list_update(lrtc_desktop_media_list_t* list, bool force_reload, bool get_thumbnail);
int LUMENRTC_CALL lrtc_impl_dtmf_sender_can_insert(lrtc_dtmf_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_dtmf_sender_comma_delay(lrtc_dtmf_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_dtmf_sender_duration(lrtc_dtmf_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_dtmf_sender_insert(lrtc_dtmf_sender_t* sender, const char* tones, int duration, int inter_tone_gap, int comma_delay);
int LUMENRTC_CALL lrtc_impl_dtmf_sender_inter_tone_gap(lrtc_dtmf_sender_t* sender);
void LUMENRTC_CALL lrtc_impl_dtmf_sender_release(lrtc_dtmf_sender_t* sender);
void LUMENRTC_CALL lrtc_impl_dtmf_sender_set_callbacks(lrtc_dtmf_sender_t* sender, const lrtc_dtmf_sender_callbacks_t* callbacks, void* user_data);
int32_t LUMENRTC_CALL lrtc_impl_dtmf_sender_tones(lrtc_dtmf_sender_t* sender, char* buffer, uint32_t buffer_len);
lrtc_factory_t* LUMENRTC_CALL lrtc_impl_factory_create(void);
lrtc_audio_source_t* LUMENRTC_CALL lrtc_impl_factory_create_audio_source(lrtc_factory_t* factory, const char* label, lrtc_audio_source_type source_type, const lrtc_audio_options_t* options);
lrtc_audio_track_t* LUMENRTC_CALL lrtc_impl_factory_create_audio_track(lrtc_factory_t* factory, lrtc_audio_source_t* source, const char* track_id);
lrtc_video_source_t* LUMENRTC_CALL lrtc_impl_factory_create_desktop_source(lrtc_factory_t* factory, lrtc_desktop_capturer_t* capturer, const char* label, lrtc_media_constraints_t* constraints);
lrtc_media_stream_t* LUMENRTC_CALL lrtc_impl_factory_create_stream(lrtc_factory_t* factory, const char* stream_id);
lrtc_video_source_t* LUMENRTC_CALL lrtc_impl_factory_create_video_source(lrtc_factory_t* factory, lrtc_video_capturer_t* capturer, const char* label, lrtc_media_constraints_t* constraints);
lrtc_video_track_t* LUMENRTC_CALL lrtc_impl_factory_create_video_track(lrtc_factory_t* factory, lrtc_video_source_t* source, const char* track_id);
lrtc_audio_device_t* LUMENRTC_CALL lrtc_impl_factory_get_audio_device(lrtc_factory_t* factory);
lrtc_desktop_device_t* LUMENRTC_CALL lrtc_impl_factory_get_desktop_device(lrtc_factory_t* factory);
void LUMENRTC_CALL lrtc_impl_factory_get_rtp_receiver_capabilities(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
void LUMENRTC_CALL lrtc_impl_factory_get_rtp_sender_capabilities(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
void LUMENRTC_CALL lrtc_impl_factory_get_rtp_sender_codec_mime_types(lrtc_factory_t* factory, lrtc_media_type media_type, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
lrtc_video_device_t* LUMENRTC_CALL lrtc_impl_factory_get_video_device(lrtc_factory_t* factory);
lrtc_result_t LUMENRTC_CALL lrtc_impl_factory_initialize(lrtc_factory_t* factory);
void LUMENRTC_CALL lrtc_impl_factory_release(lrtc_factory_t* factory);
void LUMENRTC_CALL lrtc_impl_factory_terminate(lrtc_factory_t* factory);
lrtc_result_t LUMENRTC_CALL lrtc_impl_initialize(void);
void LUMENRTC_CALL lrtc_impl_logging_remove_callback(void);
void LUMENRTC_CALL lrtc_impl_logging_set_callback(int severity, lrtc_log_message_cb callback, void* user_data);
void LUMENRTC_CALL lrtc_impl_logging_set_min_level(int severity);
void LUMENRTC_CALL lrtc_impl_media_constraints_add_mandatory(lrtc_media_constraints_t* constraints, const char* key, const char* value);
void LUMENRTC_CALL lrtc_impl_media_constraints_add_optional(lrtc_media_constraints_t* constraints, const char* key, const char* value);
lrtc_media_constraints_t* LUMENRTC_CALL lrtc_impl_media_constraints_create(void);
void LUMENRTC_CALL lrtc_impl_media_constraints_release(lrtc_media_constraints_t* constraints);
int32_t LUMENRTC_CALL lrtc_impl_media_source_get_id(lrtc_media_source_t* source, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_media_source_get_name(lrtc_media_source_t* source, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_media_source_get_type(lrtc_media_source_t* source);
void LUMENRTC_CALL lrtc_impl_media_source_release(lrtc_media_source_t* source);
bool LUMENRTC_CALL lrtc_impl_media_stream_add_audio_track(lrtc_media_stream_t* stream, lrtc_audio_track_t* track);
bool LUMENRTC_CALL lrtc_impl_media_stream_add_video_track(lrtc_media_stream_t* stream, lrtc_video_track_t* track);
int32_t LUMENRTC_CALL lrtc_impl_media_stream_get_id(lrtc_media_stream_t* stream, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_media_stream_get_label(lrtc_media_stream_t* stream, char* buffer, uint32_t buffer_len);
void LUMENRTC_CALL lrtc_impl_media_stream_release(lrtc_media_stream_t* stream);
bool LUMENRTC_CALL lrtc_impl_media_stream_remove_audio_track(lrtc_media_stream_t* stream, lrtc_audio_track_t* track);
bool LUMENRTC_CALL lrtc_impl_media_stream_remove_video_track(lrtc_media_stream_t* stream, lrtc_video_track_t* track);
int LUMENRTC_CALL lrtc_impl_peer_connection_add_audio_track(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const char** stream_ids, uint32_t stream_id_count);
lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_audio_track_sender(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const char** stream_ids, uint32_t stream_id_count);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_audio_track_transceiver(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_audio_track_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_audio_track_t* track, const lrtc_rtp_transceiver_init_t* init);
void LUMENRTC_CALL lrtc_impl_peer_connection_add_ice_candidate(lrtc_peer_connection_t* pc, const char* sdp_mid, int sdp_mline_index, const char* candidate);
int LUMENRTC_CALL lrtc_impl_peer_connection_add_ice_candidate_ex(lrtc_peer_connection_t* pc, const char* sdp_mid, int sdp_mline_index, const char* candidate);
bool LUMENRTC_CALL lrtc_impl_peer_connection_add_stream(lrtc_peer_connection_t* pc, lrtc_media_stream_t* stream);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_transceiver(lrtc_peer_connection_t* pc, lrtc_media_type media_type);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_media_type media_type, const lrtc_rtp_transceiver_init_t* init);
int LUMENRTC_CALL lrtc_impl_peer_connection_add_video_track(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const char** stream_ids, uint32_t stream_id_count);
lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_video_track_sender(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const char** stream_ids, uint32_t stream_id_count);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_video_track_transceiver(lrtc_peer_connection_t* pc, lrtc_video_track_t* track);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_add_video_track_transceiver_with_init(lrtc_peer_connection_t* pc, lrtc_video_track_t* track, const lrtc_rtp_transceiver_init_t* init);
void LUMENRTC_CALL lrtc_impl_peer_connection_close(lrtc_peer_connection_t* pc);
lrtc_peer_connection_t* LUMENRTC_CALL lrtc_impl_peer_connection_create(lrtc_factory_t* factory, const lrtc_rtc_config_t* config, lrtc_media_constraints_t* constraints, const lrtc_peer_connection_callbacks_t* callbacks, void* user_data);
void LUMENRTC_CALL lrtc_impl_peer_connection_create_answer(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data, lrtc_media_constraints_t* constraints);
lrtc_data_channel_t* LUMENRTC_CALL lrtc_impl_peer_connection_create_data_channel(lrtc_peer_connection_t* pc, const char* label, int ordered, int reliable, int max_retransmit_time, int max_retransmits, const char* protocol, int negotiated, int id);
void LUMENRTC_CALL lrtc_impl_peer_connection_create_offer(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data, lrtc_media_constraints_t* constraints);
void LUMENRTC_CALL lrtc_impl_peer_connection_get_local_description(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data);
lrtc_rtp_receiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_get_receiver(lrtc_peer_connection_t* pc, uint32_t index);
void LUMENRTC_CALL lrtc_impl_peer_connection_get_receiver_stats(lrtc_peer_connection_t* pc, lrtc_rtp_receiver_t* receiver, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
void LUMENRTC_CALL lrtc_impl_peer_connection_get_remote_description(lrtc_peer_connection_t* pc, lrtc_sdp_success_cb success, lrtc_sdp_error_cb failure, void* user_data);
lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_impl_peer_connection_get_sender(lrtc_peer_connection_t* pc, uint32_t index);
void LUMENRTC_CALL lrtc_impl_peer_connection_get_sender_stats(lrtc_peer_connection_t* pc, lrtc_rtp_sender_t* sender, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
void LUMENRTC_CALL lrtc_impl_peer_connection_get_stats(lrtc_peer_connection_t* pc, lrtc_stats_success_cb success, lrtc_stats_failure_cb failure, void* user_data);
lrtc_rtp_transceiver_t* LUMENRTC_CALL lrtc_impl_peer_connection_get_transceiver(lrtc_peer_connection_t* pc, uint32_t index);
uint32_t LUMENRTC_CALL lrtc_impl_peer_connection_receiver_count(lrtc_peer_connection_t* pc);
void LUMENRTC_CALL lrtc_impl_peer_connection_release(lrtc_peer_connection_t* pc);
bool LUMENRTC_CALL lrtc_impl_peer_connection_remove_stream(lrtc_peer_connection_t* pc, lrtc_media_stream_t* stream);
int LUMENRTC_CALL lrtc_impl_peer_connection_remove_track(lrtc_peer_connection_t* pc, lrtc_rtp_sender_t* sender);
void LUMENRTC_CALL lrtc_impl_peer_connection_restart_ice(lrtc_peer_connection_t* pc);
uint32_t LUMENRTC_CALL lrtc_impl_peer_connection_sender_count(lrtc_peer_connection_t* pc);
void LUMENRTC_CALL lrtc_impl_peer_connection_set_callbacks(lrtc_peer_connection_t* pc, const lrtc_peer_connection_callbacks_t* callbacks, void* user_data);
int LUMENRTC_CALL lrtc_impl_peer_connection_set_codec_preferences(lrtc_peer_connection_t* pc, lrtc_media_type media_type, const char** mime_types, uint32_t mime_type_count);
void LUMENRTC_CALL lrtc_impl_peer_connection_set_local_description(lrtc_peer_connection_t* pc, const char* sdp, const char* type, lrtc_void_cb success, lrtc_sdp_error_cb failure, void* user_data);
void LUMENRTC_CALL lrtc_impl_peer_connection_set_remote_description(lrtc_peer_connection_t* pc, const char* sdp, const char* type, lrtc_void_cb success, lrtc_sdp_error_cb failure, void* user_data);
int LUMENRTC_CALL lrtc_impl_peer_connection_set_transceiver_codec_preferences(lrtc_peer_connection_t* pc, lrtc_rtp_transceiver_t* transceiver, const char** mime_types, uint32_t mime_type_count);
uint32_t LUMENRTC_CALL lrtc_impl_peer_connection_transceiver_count(lrtc_peer_connection_t* pc);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_encoding_count(lrtc_rtp_receiver_t* receiver);
lrtc_audio_track_t* LUMENRTC_CALL lrtc_impl_rtp_receiver_get_audio_track(lrtc_rtp_receiver_t* receiver);
int LUMENRTC_CALL lrtc_impl_rtp_receiver_get_degradation_preference(lrtc_rtp_receiver_t* receiver);
int LUMENRTC_CALL lrtc_impl_rtp_receiver_get_dtls_info(lrtc_rtp_receiver_t* receiver, lrtc_dtls_transport_info_t* info);
int LUMENRTC_CALL lrtc_impl_rtp_receiver_get_encoding_info(lrtc_rtp_receiver_t* receiver, uint32_t index, lrtc_rtp_encoding_info_t* info);
int32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_get_encoding_rid(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_get_encoding_scalability_mode(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_get_id(lrtc_rtp_receiver_t* receiver, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_rtp_receiver_get_media_type(lrtc_rtp_receiver_t* receiver);
int32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_get_parameters_mid(lrtc_rtp_receiver_t* receiver, char* buffer, uint32_t buffer_len);
lrtc_media_stream_t* LUMENRTC_CALL lrtc_impl_rtp_receiver_get_stream(lrtc_rtp_receiver_t* receiver, uint32_t index);
int32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_get_stream_id(lrtc_rtp_receiver_t* receiver, uint32_t index, char* buffer, uint32_t buffer_len);
lrtc_video_track_t* LUMENRTC_CALL lrtc_impl_rtp_receiver_get_video_track(lrtc_rtp_receiver_t* receiver);
void LUMENRTC_CALL lrtc_impl_rtp_receiver_release(lrtc_rtp_receiver_t* receiver);
int LUMENRTC_CALL lrtc_impl_rtp_receiver_set_jitter_buffer_min_delay(lrtc_rtp_receiver_t* receiver, double delay_seconds);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_stream_count(lrtc_rtp_receiver_t* receiver);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_receiver_stream_id_count(lrtc_rtp_receiver_t* receiver);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_sender_encoding_count(lrtc_rtp_sender_t* sender);
lrtc_audio_track_t* LUMENRTC_CALL lrtc_impl_rtp_sender_get_audio_track(lrtc_rtp_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_rtp_sender_get_degradation_preference(lrtc_rtp_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_rtp_sender_get_dtls_info(lrtc_rtp_sender_t* sender, lrtc_dtls_transport_info_t* info);
lrtc_dtmf_sender_t* LUMENRTC_CALL lrtc_impl_rtp_sender_get_dtmf_sender(lrtc_rtp_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_rtp_sender_get_encoding_info(lrtc_rtp_sender_t* sender, uint32_t index, lrtc_rtp_encoding_info_t* info);
int32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_encoding_rid(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_encoding_scalability_mode(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len);
int32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_id(lrtc_rtp_sender_t* sender, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_rtp_sender_get_media_type(lrtc_rtp_sender_t* sender);
int32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_parameters_mid(lrtc_rtp_sender_t* sender, char* buffer, uint32_t buffer_len);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_ssrc(lrtc_rtp_sender_t* sender);
int32_t LUMENRTC_CALL lrtc_impl_rtp_sender_get_stream_id(lrtc_rtp_sender_t* sender, uint32_t index, char* buffer, uint32_t buffer_len);
lrtc_video_track_t* LUMENRTC_CALL lrtc_impl_rtp_sender_get_video_track(lrtc_rtp_sender_t* sender);
void LUMENRTC_CALL lrtc_impl_rtp_sender_release(lrtc_rtp_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_rtp_sender_replace_audio_track(lrtc_rtp_sender_t* sender, lrtc_audio_track_t* track);
int LUMENRTC_CALL lrtc_impl_rtp_sender_replace_video_track(lrtc_rtp_sender_t* sender, lrtc_video_track_t* track);
int LUMENRTC_CALL lrtc_impl_rtp_sender_set_encoding_parameters(lrtc_rtp_sender_t* sender, const lrtc_rtp_encoding_settings_t* settings);
int LUMENRTC_CALL lrtc_impl_rtp_sender_set_encoding_parameters_at(lrtc_rtp_sender_t* sender, uint32_t index, const lrtc_rtp_encoding_settings_t* settings);
int LUMENRTC_CALL lrtc_impl_rtp_sender_set_stream_ids(lrtc_rtp_sender_t* sender, const char** stream_ids, uint32_t stream_id_count);
uint32_t LUMENRTC_CALL lrtc_impl_rtp_sender_stream_id_count(lrtc_rtp_sender_t* sender);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_current_direction(lrtc_rtp_transceiver_t* transceiver);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_direction(lrtc_rtp_transceiver_t* transceiver);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_fired_direction(lrtc_rtp_transceiver_t* transceiver);
int32_t LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_id(lrtc_rtp_transceiver_t* transceiver, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_media_type(lrtc_rtp_transceiver_t* transceiver);
int32_t LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_mid(lrtc_rtp_transceiver_t* transceiver, char* buffer, uint32_t buffer_len);
lrtc_rtp_receiver_t* LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_receiver(lrtc_rtp_transceiver_t* transceiver);
lrtc_rtp_sender_t* LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_sender(lrtc_rtp_transceiver_t* transceiver);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_stopped(lrtc_rtp_transceiver_t* transceiver);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_get_stopping(lrtc_rtp_transceiver_t* transceiver);
void LUMENRTC_CALL lrtc_impl_rtp_transceiver_release(lrtc_rtp_transceiver_t* transceiver);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_set_direction(lrtc_rtp_transceiver_t* transceiver, int direction, char* error, uint32_t error_len);
int LUMENRTC_CALL lrtc_impl_rtp_transceiver_stop(lrtc_rtp_transceiver_t* transceiver, char* error, uint32_t error_len);
void LUMENRTC_CALL lrtc_impl_terminate(void);
bool LUMENRTC_CALL lrtc_impl_video_capturer_capture_started(lrtc_video_capturer_t* capturer);
void LUMENRTC_CALL lrtc_impl_video_capturer_release(lrtc_video_capturer_t* capturer);
bool LUMENRTC_CALL lrtc_impl_video_capturer_start(lrtc_video_capturer_t* capturer);
void LUMENRTC_CALL lrtc_impl_video_capturer_stop(lrtc_video_capturer_t* capturer);
lrtc_video_capturer_t* LUMENRTC_CALL lrtc_impl_video_device_create_capturer(lrtc_video_device_t* device, const char* name, uint32_t index, size_t width, size_t height, size_t target_fps);
int32_t LUMENRTC_CALL lrtc_impl_video_device_get_device_name(lrtc_video_device_t* device, uint32_t index, char* name, uint32_t name_length, char* unique_id, uint32_t unique_id_length);
uint32_t LUMENRTC_CALL lrtc_impl_video_device_number_of_devices(lrtc_video_device_t* device);
void LUMENRTC_CALL lrtc_impl_video_device_release(lrtc_video_device_t* device);
int LUMENRTC_CALL lrtc_impl_video_frame_copy_i420(lrtc_video_frame_t* frame, uint8_t* dst_y, int dst_stride_y, uint8_t* dst_u, int dst_stride_u, uint8_t* dst_v, int dst_stride_v);
const uint8_t* LUMENRTC_CALL lrtc_impl_video_frame_data_u(lrtc_video_frame_t* frame);
const uint8_t* LUMENRTC_CALL lrtc_impl_video_frame_data_v(lrtc_video_frame_t* frame);
const uint8_t* LUMENRTC_CALL lrtc_impl_video_frame_data_y(lrtc_video_frame_t* frame);
int LUMENRTC_CALL lrtc_impl_video_frame_height(lrtc_video_frame_t* frame);
void LUMENRTC_CALL lrtc_impl_video_frame_release(lrtc_video_frame_t* frame);
lrtc_video_frame_t* LUMENRTC_CALL lrtc_impl_video_frame_retain(lrtc_video_frame_t* frame);
int LUMENRTC_CALL lrtc_impl_video_frame_stride_u(lrtc_video_frame_t* frame);
int LUMENRTC_CALL lrtc_impl_video_frame_stride_v(lrtc_video_frame_t* frame);
int LUMENRTC_CALL lrtc_impl_video_frame_stride_y(lrtc_video_frame_t* frame);
int LUMENRTC_CALL lrtc_impl_video_frame_to_argb(lrtc_video_frame_t* frame, uint8_t* dst_argb, int dst_stride_argb, int dest_width, int dest_height, int format);
int LUMENRTC_CALL lrtc_impl_video_frame_width(lrtc_video_frame_t* frame);
lrtc_video_sink_t* LUMENRTC_CALL lrtc_impl_video_sink_create(const lrtc_video_sink_callbacks_t* callbacks, void* user_data);
void LUMENRTC_CALL lrtc_impl_video_sink_release(lrtc_video_sink_t* sink);
void LUMENRTC_CALL lrtc_impl_video_source_release(lrtc_video_source_t* source);
void LUMENRTC_CALL lrtc_impl_video_track_add_sink(lrtc_video_track_t* track, lrtc_video_sink_t* sink);
int LUMENRTC_CALL lrtc_impl_video_track_get_enabled(lrtc_video_track_t* track);
int32_t LUMENRTC_CALL lrtc_impl_video_track_get_id(lrtc_video_track_t* track, char* buffer, uint32_t buffer_len);
int LUMENRTC_CALL lrtc_impl_video_track_get_state(lrtc_video_track_t* track);
void LUMENRTC_CALL lrtc_impl_video_track_release(lrtc_video_track_t* track);
void LUMENRTC_CALL lrtc_impl_video_track_remove_sink(lrtc_video_track_t* track, lrtc_video_sink_t* sink);
int LUMENRTC_CALL lrtc_impl_video_track_set_enabled(lrtc_video_track_t* track, int enabled);

#ifdef __cplusplus
}
#endif
